import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/Header";
import Footer from "@/component/Footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased grid grid-rows-[2rem_1fr_2rem] items-start justify-items-start min-h-screen px-8 pt-0 pb-20 gap-16 sm:px-20 font-[family-name:var(--font-geist-sans)]`}
      >
        <Header />
        {children}
        <Footer />
      </body>
    </html>
  );
}
